/**
 * 命令示例映射
 */
const commandExamples = [
    'PING',
    'INFO [section]',
    'KEYS pattern',
    'GET key',
    'SET key value [EX seconds|PX milliseconds] [NX|XX]',
    'DEL key [key ...]',
    'EXISTS key [key ...]',
    'EXPIRE key seconds',
    'TTL key',
    'PTTL key',
    'TYPE key',
    'RENAME key newkey',
    'RENAMENX key newkey',
    'MOVE key db',
    'DUMP key',
    'RESTORE key ttl serialized-value',
    'PERSIST key',
    'FLUSHDB',
    'FLUSHALL',
    'DBSIZE',
    'RANDOMKEY',
    'APPEND key value',
    'STRLEN key',
    'GETRANGE key start end',
    'SETRANGE key offset value',
    'INCR key',
    'DECR key',
    'INCRBY key increment',
    'DECRBY key decrement',
    'INCRBYFLOAT key increment',
    'HSET key field value [field value ...]',
    'HGET key field',
    'HGETALL key',
    'HDEL key field [field ...]',
    'HEXISTS key field',
    'HKEYS key',
    'HVALS key',
    'HLEN key',
    'HINCRBY key field increment',
    'HINCRBYFLOAT key field increment',
    'HMSET key field value [field value ...]',
    'HMGET key field [field ...]',
    'HSCAN key cursor [MATCH pattern] [COUNT count]',
    'LPUSH key element [element ...]',
    'RPUSH key element [element ...]',
    'LPOP key [count]',
    'RPOP key [count]',
    'LLEN key',
    'LRANGE key start stop',
    'LINDEX key index',
    'LSET key index element',
    'LTRIM key start stop',
    'LREM key count element',
    'LPUSHX key element [element ...]',
    'RPUSHX key element [element ...]',
    'LINSERT key BEFORE|AFTER pivot element',
    'SADD key member [member ...]',
    'SREM key member [member ...]',
    'SMEMBERS key',
    'SCARD key',
    'SISMEMBER key member',
    'SINTER key [key ...]',
    'SUNION key [key ...]',
    'SDIFF key [key ...]',
    'SPOP key [count]',
    'SRANDMEMBER key [count]',
    'SMOVE source destination member',
    'SSCAN key cursor [MATCH pattern] [COUNT count]',
    'ZADD key score member [score member ...]',
    'ZREM key member [member ...]',
    'ZRANGE key start stop [WITHSCORES]',
    'ZREVRANGE key start stop [WITHSCORES]',
    'ZCARD key',
    'ZSCORE key member',
    'ZRANK key member',
    'ZREVRANK key member',
    'ZINCRBY key increment member',
    'ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]',
    'ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]',
    'ZCOUNT key min max',
    'ZREMRANGEBYRANK key start stop',
    'ZREMRANGEBYSCORE key min max',
    'ZSCAN key cursor [MATCH pattern] [COUNT count]',
    'MGET key [key ...]',
    'MSET key value [key value ...]',
    'MSETNX key value [key value ...]',
    'GETSET key value',
    'SETNX key value',
    'SETEX key seconds value',
    'PSETEX key milliseconds value',
    'GETBIT key offset',
    'SETBIT key offset value',
    'BITCOUNT key [start end]',
    'SELECT index',
    'AUTH password',
    'QUIT',
    'ECHO message',
    'TIME',
    'CLIENT subcommand [arg [arg ...]]',
    'CONFIG subcommand [arg [arg ...]]',
    'SCAN cursor [MATCH pattern] [COUNT count]',
    'BGREWRITEAOF',
    'BGSAVE',
    'SAVE',
    'LASTSAVE',
    'SHUTDOWN [NOSAVE|SAVE]',
    'SLAVEOF host port',
    'ROLE',
    'MONITOR',
    'DEBUG subcommand [arg [arg ...]]',
    'SLOWLOG subcommand [arg]',
    'OBJECT subcommand [arg [arg ...]]',
    'MIGRATE host port key destination-db timeout'
]

/**
 * 匹配命令示例
 * @param {string} command 命令
 * @returns {{matched: boolean, example: string}|{matched: boolean}} 匹配的命令示例
 */
export const matchedExample = (command) => {
    const example = commandExamples.find(example => {
        return example.toLowerCase().startsWith(command.toLowerCase())
            && command.toLowerCase() !== example.toLowerCase()
    })

    // 匹配成功
    return example ? {matched: true, result: example} : {matched: false}
}